target ‘Nibble’ do
    platform :ios, '10.0'
    use_frameworks!
    pod 'MXParallaxHeader'
    pod 'ChameleonFramework/Swift'
    pod 'Stripe'
    pod 'Alamofire'
    pod 'FaveButton', '~> 2.0.3'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Messaging'
    pod 'PopupDialog', '~> 0.5'
    pod 'GMStepper'
    pod 'SCLAlertView'
    pod 'JGProgressHUD'
    pod 'Kingfisher'
    pod 'Bolts'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'SACountingLabel'
    pod 'IQKeyboardManagerSwift'
    pod 'RZTransitions'
end
